### ISSUE TITLE
Allow nested extending

### ISSUE THREAD

**Issue by razonyang** [hugomods/decap-cms#88]
```yaml
params:
  decap_cms:
    _configs:
      foo:
        _extends:
          - field_title
        fields:
          - {label: Foo, name: foo, widget: string}
      bar:
        _extends:
          - foo
        fields:
          - {label: Bar, name: bar, widget: string}
    collection:
      foobar:
        _extends:
          - bar
```

Take above as an example, the `bar` extends `foo` configuration, which extends `field_title`.

As a result, the `foobar` collection should be equal to:

```yaml
foobar:
  fields:
    - {label: Title, name: title, widget: string}
    - {label: Foo, name: foo, widget: string}
    - {label: Bar, name: bar, widget: string}
```
